### ISSUE TITLE
Form fields for submitting and adding a project 

### ISSUE THREAD

**Issue by kristinashu** [mozilla/science.mozilla.org#110]
The current submission form is very long (especially if someone doesn't even know if their project will go on the site or not). 

![screenshot-www mozillascience org 2016-03-30 14-11-47](https://cloud.githubusercontent.com/assets/1068783/14252668/383c3ff0-fa3d-11e5-8a4f-316b6e6c1eb3.png)

I'm wondering if we can split up the form into two separate ones: 
- part 1: initial submission to see if the project is a good candidate for the site (this would be accessed on the project landing page https://redpen.io/jc2e62ed8f6f3f6ef5) 
- part 2: once one of you has reviewed the project and you think it would be good on the site, then we send the second part of the form with the rest of the questions

I'm wondering if you have suggestions on how to spit up the questions. Ie which would be the key questions you would need to know to determine if the project would be a good candidate.

Here's is a rough wireframe of the initial form but I'd love to simplify it even more https://redpen.io/dq01e5e243a5cd0634

cc @hannahkane @acabunoc @kaythaney @auremoser @zee-moz @stephwright

**Comment by hannahkane** [comment]
I like the simplifications you've made already, and I realize this question is mostly for the Science team to answer, since they'll know what information is critical for evaluating a project. 

I imagine most of the fields are quite easy to answer, but perhaps we could reduce the number of textarea questions from three to two by combining "Short description" and "How does this benefit the scientific community" into a single question like, "Describe your project and how it benefits the scientific community?" I'm thinking those questions might be fundamentally linked, but I might be off base with that assumption.

**Comment by hannahkane** [comment]
Moving this out of the April 8 milestone, since it's Phase 2

**Comment by kristinashu** [comment]
Oh I think we can close this. We've reduced the number of questions and what they are https://redpen.io/dq01e5e243a5cd0634
