### ISSUE TITLE
Build front end for projects and pages functionality

### ISSUE THREAD

**Issue by alanmoo** [mozilla/science.mozilla.org#114]
https://redpen.io/p/eb9d7534bcf4dfcc17 3.0 and 3.1 content. Includes search/sort/filter

**Comment by hannahkane** [comment]
Just to clarify - we are *not* aiming to do the "Sign in to join the project" part for launch, right? @acabunoc @kristinashu @simonwex

**Comment by kristinashu** [comment]
I agree, we are not aiming to do the "Sign in to join the project" part for launch. Project details page would just be (https://redpen.io/pj5fe2e9cbbd51a880):
![04_projectdetailsnotsignedin 2x copy](https://cloud.githubusercontent.com/assets/1068783/14479006/57085f2a-00cf-11e6-97be-a494b9221e0f.jpg)

Not sure about the "Add your project" form. The button link will not appear on the site (at one time we talked about allowing anyone to submit a project but they have since decided to limit access. People will have to have been emailed the url to access the [form](https://redpen.io/dq01e5e243a5cd0634) (same as on current site). Page isn’t password protected or anything, there just isn’t a link to it on the site.) So regardless of the phase, we wouldn’t have the link. BUT I'm not sure if we need the form or not for launch?

Also not sure what we decided for Search/Filter/Sort functionality? I would say filters are the most important but we could do without search, and sort would be the least important.

**Comment by gvn** [comment]
@hannahkane That's my understanding as well.

**Comment by acabunoc** [comment]
I don't think the form is needed for launch - we should require auth on the form so we know the submitter.

I left a note in the redpen about "add your project" text -- with the 'hidden' link, some guidance on *how* projects get listed would be good. Currently they are either project that have gone through a Working Open Workshop, or featured projects participating in the global sprint or MozFest.

Agree with @kristinashu on search/filter/sort functionality importance

**Comment by hannahkane** [comment]
Thanks for the reminder about the "Add your project" workflow. I'd forgotten. @kristinashu - will you add the copy that @acabunoc provided in the copy doc to the Phase 1 comp?

Flagging @gideonthomas and @alicoding regarding the lesser importance of Search and Sorting, especially since we'd estimated that Search would be more effort than Sorting and Filtering.

**Comment by alanmoo** [comment]
This has been merged in
