### ISSUE TITLE
[design QA] newsletter signup styling

### ISSUE THREAD

**Issue by kristinashu** [mozilla/science.mozilla.org#234]
Hover state for button should be like https://mozilla-foundation-research.herokuapp.com/globalweb/

"your email" and "subscribe" text are a pixel or two too high

Staging:
<img width="321" alt="screen shot 2016-04-21 at 2 03 43 pm" src="https://cloud.githubusercontent.com/assets/1068783/14724340/4fb52288-07ca-11e6-9130-cf11482d6012.png">

In 'tablet' view:
- please center everything
- put title on one line
staging:
<img width="691" alt="screen shot 2016-04-21 at 2 07 25 pm" src="https://cloud.githubusercontent.com/assets/1068783/14724356/7026a988-07ca-11e6-9fe7-030031118ed4.png">

**Comment by alanmoo** [comment]
This component breaks the mobile view, we really need to fix this before launch.

**Comment by alanmoo** [comment]
I'm submitting a PR for this that should fix everything except for the input/button pixel text- that's an issue being caused by the Fira Font- when I change inputs back to the system font, it looks as it should. I'm hesitant to make adjustments to input elements based on that, because I've seen this type of fix spiral out of control in the past.
