### ISSUE TITLE
Finalize resource categories 

### ISSUE THREAD

**Issue by kristinashu** [mozilla/science.mozilla.org#269]
All the resources are here https://docs.google.com/spreadsheets/d/1aQhmnDO4zYt24sD8ItYeesbAn2TUiHzKyllSkzs4VN0/edit#gid=0

We just need to finalize the filter categories. We are trying to limit the number of categories and keep them as broad as possible so multiple resources will show up under the filter.

Based on - Comps for Resources page #126

**Comment by acabunoc** [comment]
From @stephwright:

>I want to +1 Zannah's suggestion in the call today that we do broader categories (e.g. Coding  vs GitHub or R)

>Think about how folks will come searching for information and also what keywords are already in the titles and can be searched that way.  Particularly if these resources are already being associated w/ a page on the topic (e.g. Study Groups) Filtering is best used for broader concepts that aren't obvious through other textual info associated with the record

>^^ I've now reached my maximum limit of librarian speak for today

**Comment by zee-moz** [comment]
Here are my suggestions for broad categories:

**collaboration tools** (github, git, etc)
**community building **(events, personas, codes of conduct etc)
**open communications** (blogs, de-jargonzing, pitches)
**project planning **(roadmapping, strategy exercises)
**coding** (SG lessons, r, command line, etc)
**open data** (all open data stuff)

I think we can get rid of "working open" as a category since it covers everything above.
We would also need these filters, for people who are actually fellows or SG leads. But as categories they are not descriptive.

**fellowship resources** (onboarding materials, plus some items from above)
**study group leadership** (onboarding materials, plus some items from above)

**Comment by stephwright** [comment]
Are we linking resources on the Fellowship page and Study Group page?  If so, is there something added by creating a filter for the Study Group and Fellowship category?

**Comment by zee-moz** [comment]
@stephwright if we're linking, then no, we don't need filters!

**Comment by stephwright** [comment]
:+1:

**Comment by kristinashu** [comment]
Thanks everyone! I've added a third tab to the spreadsheet called "New Broader Categories" https://docs.google.com/a/mozilla.com/spreadsheets/d/1aQhmnDO4zYt24sD8ItYeesbAn2TUiHzKyllSkzs4VN0/edit?usp=sharing

Any chance someone could check off which categories each resource should show up under? One resource can be in multiple categories.

**Comment by stephwright** [comment]
I've taken a first stab... some I wasn't sure

**Comment by acabunoc** [comment]
We were also using the 'study group' category to show which ones should show up on the study group page (under study group lessons) -- can we show all the 'coding' ones there now?

**Comment by hannahkane** [comment]
Moving to May 20 to wrap

**Comment by gideonthomas** [comment]
This is done.
