### ISSUE TITLE
Format the time shown for geo-specific events

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/science.mozilla.org#385]
On the API, we store the start and end times for an event in UTC. We also provide a timezone field (which apparently has not been populated in the database yet) that is a string which helps convert those UTC times into a time that is appropriate for that event.

Based on a quick chat with @alanmoo, this might be relevant only for events that are not online and are occurring at a specific location. An example of such an event is [here](http://science-mozilla-org-staging.herokuapp.com/programs/programs/events/working-open-workshop-mixer-february-4th)

Work involved:
1. The front-end would need to decide on a specific type of string that they would store as the "timezone" in the API. This is what will be used on the displayed event page to translate the UTC times that are passed  in from the API into a time that is specific to the event's location.
2. One API piece that will need to be done once the schema for the timezone field has been defined is populating the timezone data for each event in the db. Issue filed here: #386

**Comment by alanmoo** [comment]
@acabunoc we could use some guidance on this.

Currently, all events shorter than a day display their time in the visitor's time zone. Is that OK, even for events that are fixed to a location [like the one Gideon referenced](http://science-mozilla-org-staging.herokuapp.com/programs/programs/events/working-open-workshop-mixer-february-4th)? If so, I believe this issue can be closed.

**Comment by acabunoc** [comment]
No, if the event occurs at a specific location the time *should* be in the local timezone. However, I'm happy moving this to phase 2.

**Comment by alanmoo** [comment]
Ok, we're going to figure out how this is indicated then- I was thinking a checkbox when creating an event that indicates it's meant for in-person attendees only (not an online event).

**Comment by alanmoo** [comment]
See #535

**Comment by arush0311** [comment]
As far as I understand these are the changes we have to make:
- Figure out whether the the event to be added is virtual event or not
- If No, what is the timezone of event from the location entered and check the local timezone checkbox from @alanmoo's comment
- If checkbox is checked send timezone top api server along with all other info.

**Comment by alanmoo** [comment]
Sounds about right, at least in terms of what we are generally tying to do. The events are created on the Django server, so this may require a little bit of admin work. However, don't go rewriting anything extensively; this can probably be done with a light touch to include the data we need on the back end and then updating the front end to check for a variable and determine how to render it.

Remember that we need to account for not only what time zone the event is, but what time zone the creator is so that it's clear. (For example, @auremoser might create an event in NYC while she's in Europe)

**Comment by arush0311** [comment]
or perhaps convert the timezone field from input to select with timezone options along with none. (None will specify virtual event).
@alanmoo getting creator's timezone will require some javascript, unless django provides a way to do that. I will look into that.

**Comment by alanmoo** [comment]
Even if the time zone is a select element, i think we need a Boolean so the front end knows to convert time or not.

Example:
I create an event, 5-6pm Eastern. I need to give it a time zone and still say "virtual" so that the time gets rendered appropriately to users on the front end (people in California would see 2-3pm).

If I don't indicate it's virtual, California users would see 5-6 which would be wrong, or 5-6 Eastern which means they need to convert mentally, which is less than ideal.

**Comment by alanmoo** [comment]
We don't need to get creator's time zone, just make sure they have to put an event time zone in when creating an event
