### ISSUE TITLE
Make the admin interface for the API more user-friendly

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/science.mozilla.org#424]
Would like to have feedback on what we can improve in the admin interface to make adding/modifying/deleting data easier. Are there any issues that you have while navigating data? 

Suggestions are welcome based on your use case.

cc @acabunoc, @auremoser

**Comment by acabunoc** [comment]
It would be nice to have a search for adding users to an event (instead of scrolling through everyone)

**Comment by auremoser** [comment]
I'm sorry for how late I am here. This interface is lovely! Thank you! Just to be clear, we'll be using 
* WP for the blog entries
* Django Admin for the Events, Resources, Study Groups
* Github for the custom pages/ fellowships etcet

Anything I'm missing here or have I messed up the storage location of any assets? Meanwhile, here are some (quick) thoughts: 

### Resources

It would be nice to sort the resources alphabetically to do a quick test of how many duplicate resources we might have, or which ones might benefit from consolidation. I don't expect this to be a problem in the immediate but we're building LOTS of cross-org curriculum and adding these features now would save some headache in the future:
![screen shot 2016-06-03 at 6 00 51 pm](https://cloud.githubusercontent.com/assets/1559703/15796588/0c009060-29b5-11e6-882e-829dcd3f234f.png)

### Study Groups

It would be nice to sort the Study Groups by location just for observation and management purposes, right now, it's not too problematic because they fit on one page, but if we hit a capacity of active study groups beyond what we list currently, we'll have to paginate and it could get more difficult to manage, update, and edit entries:
![screen shot 2016-06-03 at 5 56 27 pm](https://cloud.githubusercontent.com/assets/1559703/15796518/eb549b3c-29b3-11e6-8393-04a3ec0a9aee.png)

When adding a new Study Group, it would be nice if the "regions" field was a drop down, to control the vocabulary of what you can select. the site has different regional categories, not just continents, so what is "allowed" might get confusing as it's determined by the density of study groups in that area and not by common administrative districts like "all countries" or "all continents": 
![screen shot 2016-06-03 at 5 56 44 pm](https://cloud.githubusercontent.com/assets/1559703/15796529/270100d0-29b4-11e6-8e1e-bf33ee68e952.png)

**Comment by arush0311** [comment]
Is there a format we use to insert location (or region)? Without it sorting may be not be effective.

**Comment by alanmoo** [comment]
I think inserting a new one as a free string is fine, sorting is still useful because it easily lets people visually skip a lot of rows to more easily find the item they're looking for.

**Comment by arush0311** [comment]
Perhaps a search is better for that use case

**Comment by alanmoo** [comment]
That's a possibility, but keep in mind what the ask was and what problems we're trying to solve. Also, it's been a year since these suggestions. @auremoser do they still hold up?

**Comment by auremoser** [comment]
These things would still be nice to have. If you're overwhelmed with issues however, I am used to the workflow now, so it's not that big of a deal just to close this.

I would say priority beyond these suggestions is figuring out the "timezone" thing for "events", which I believe is another issue. Currently, every event tells you how many hours behind server time your date/time is for the event, but it would be great if you could set a timezone, or prevent it from auto-changing the formula if it detects you're in another location currently. I routinely mess that up, and since there isn't a preview option I end up publishing and adjusting times after the fact.

**Comment by auremoser** [comment]
Might make sense to split these out into multiple issues, as the above possibly crosses over with #386

**Comment by HassenPy** [comment]
@auremoser, i submitted a PR with all of those changes except for the timezone issue:
https://github.com/mozilla/api.mozillascience.org/issues/78

**Comment by auremoser** [comment]
Thank you @HassenPy !

**Comment by alanmoo** [comment]
@HassenPy Sorry for the long delay in reviewing, but that looks pretty good. One thing though- with the study group sorting, I'm not quite sure that feels right to simply sort alphabetically by the city name. @auremoser what implementation were you thinking about there?

**Comment by auremoser** [comment]
City name sort would be good I think, better than alphabetical by name of study group, because often that ends up being nonstandard and unhelpful. 

I usually have a geographic memory of study group leads and groups in general, so if I were looking for something, I'd probably want to sort by region from the website, by country, and then by city name. If there's a way all might be implemented that would be wonderful. Currently, I'm the only one updating the Django interface, or searching it. 

It would be nice if the regions/continents featured on the website as categories were available to sort or group study groups:
![screen shot 2017-06-06 at 11 57 15 am](https://cloud.githubusercontent.com/assets/1559703/26823818/4f50dc3c-4aaf-11e7-94b1-d3aa601caf1f.png)

**Comment by alanmoo** [comment]
Cool. Opening #644 for that change and closing this so we don't get confused.
