### ISSUE TITLE
Rename github_contributor property keys

### ISSUE THREAD

**Issue by alanmoo** [mozilla/science.mozilla.org#461]
Example endpoint: http://api-mozillascience-staging.herokuapp.com/projects/22/?expand=users

Since users and github_contributors are used similarly, it would be helpful if the shared properties could be the same name.

Example:

````
"github_contributors": [
        {
            "github_username": "demitri",
            "avatar_url": "https://avatars.githubusercontent.com/u/64314?v=3",
            "url": "https://github.com/demitri"
        }
]
````

In addition, does the github api return a first name that we could add in there too?

Blocking #452

**Comment by gideonthomas** [comment]
@alanmoo is the collation of `users` and `github_contributors` absolutely necessary? I ask because it is a bit complicated to combine them since one property is obtained from the db and the other is dynamically populated from a github API call.

The first name is not returned in the github API call since Github has no concept of First/Last Name.

**Comment by alanmoo** [comment]
You don't need to collate, I will. I just need you to change the key names for github_contributors

-Alan

**Comment by gideonthomas** [comment]
Oh I see what you mean! We can do that!

**Comment by gideonthomas** [comment]
@alanmoo this is done on staging and production! Let me know if you want me to revert production temporarily

**Comment by alanmoo** [comment]
I'm not seeing it in production yet, but it's not being used by anything so go ahead and push it there too.
