### ISSUE TITLE
Inserting a donate button

### ISSUE THREAD

**Issue by amjadm61** [mozilla/science.mozilla.org#501]
Insert a donate button in the footer
![capture](https://cloud.githubusercontent.com/assets/4783625/15936958/a752cdba-2e8a-11e6-9793-4e6f8334cac9.PNG)

**Comment by hannahkane** [comment]
Great idea, @amjadm61!

In fact, I'm going to close this ticket because I think this idea should apply to more than just this website. Opening https://github.com/MozillaFoundation/Design/issues/210 to discuss the idea of having it on all footers across the various Mozilla Foundation web properties.

Thank you for the suggestion!
