### ISSUE TITLE
Improvements for Events

### ISSUE THREAD

**Issue by hannahkane** [mozilla/science.mozilla.org#535]
From @auremoser:

- It would be cool to have access to the S3 bucket where image urls are stored, with the proper dimensions for the event thumbnails; right now, I'm reusing the same 2 from previous calls because I don't want to put a random imgur in the Event field for Image URL - **update** @auremoser has access, but we should add UI so that other users can upload an image (https://github.com/mozilla/science.mozilla.org/issues/530)
- I'd love to have a set timezone for events, or to be able to set it myself, right now it involves some math and guessing to get the timing of a call right "Note: You are 4 hours behind server time." is helpful but still involves some counting, there's a field for Timezone but I'm not sure it works (if so I'll totally use it though) (filed here: https://github.com/mozilla/science.mozilla.org/issues/548)
- It would be nice to have some small grey text explaining the difference between Short Description and Description in terms of where they fall on the page and whether they should be redundant because they display in different places, or not because they display one after another (filed here: #549)
- Sorting attendees and facilitators or even just alphabetizing usernames would be awesome (https://github.com/mozilla/science.mozilla.org/issues/550)
- Probably not a priority, but it would be cool to add study groups to the relevant study group learning calls, in the way that "Projects" are listed. I'm thinking of setting up more regional checkins where a few study groups would join one call, and it would be nice to list them as attendees! Not super important though.

**Comment by alanmoo** [comment]
Proposal for the time zone issue (which can be extended to events APIs across our web properties):

When inputting an event time, there should be a time zone select box associated with it, which defaults to the user's (person inputting the time) current time zone.
There should be a checkbox next to it to "lock" the event to that time.

Example: A meeting is happening from 12PM-1PM EST. User in EST is inputting this event data.

* Checked Box: Show events at that time, no matter where a visitor is located ("Talk 1: 9AM-10AM EST"). 
* Unchecked Box: Event shows up in the time zone of a person visiting the site (For a user in California: "Talk 1: 6AM-7AM PST")

Does this make sense?

**Comment by acabunoc** [comment]
Also: https://github.com/mozilla/science.mozilla.org/issues/424

**Comment by hannahkane** [comment]
@auremoser - can you clarify your fourth bullet point? Are you talking about letting users sort attendees/facilitators?

**Comment by acabunoc** [comment]
@hannahkane I think it's when you're adding a new event in the django admin. Adding facilitators to the event is hard since you can't sort all the people. They appear in a giant list in the order they were created, I believe.

@auremoser feel free to correct me!

**Comment by auremoser** [comment]
+1 to @acabunoc 's read. It was about adding a new event in the django admin and adding facilitators/participants manually.

**Comment by hannahkane** [comment]
One more question for you, @auremoser. On the last bullet point, can you clarify if the relationship between the Study Groups and the events would be more like an "Invited" list or an "Attending" list?  That is, is it more like you, when adding the event, saying which Study Groups *should* attend, or is it more like an RSVP tool for Study Groups to say they *are* attending?

Also, since we don't have much meta data about the Study Groups (just name, location, region, and a url), the cards pattern we used for Projects might not apply. It might be better to just show a list of Study Groups, for example. Thoughts on that?

**Comment by hannahkane** [comment]
Aiming to close this ticket once we have separate issues for each item in the original list.

**Comment by auremoser** [comment]
Thanks @hannahkane All study groups are always invited but there's no "RSVP" system and people sometimes drop in/bail at the last minute; I'm o.k. not having an RSVP setup. You're right about the lack of metadata; I think a list is fine; a list-form matches the format of the [Study Group page](https://science.mozilla.org/programs/studygroups) anyway.

Mostly, I would like:

* to add one study group lead/study group as a "facilitator" (I try to select one emcee from the leads every call)
* to post-facto add Study groups as "attendees" or "featured" groups, because there's no RSVP and no certainty about who attended until after the call, i'd like to be able to edit the event so that it has an archive of attending study groups, to gauge participation in the calls and build better metrics around the program, if that makes sense. Currently, the only way to know who attended is to click into the Etherpad and look at the roll call, so it would be nice to have a more "public" view of the roll call for the SG calls. I could add people who promised to attend ahead of the event, but I would probably go back and adjust attendance after the actual call based on who actually showed up

So, my thoughts around this were bit of a departure from the original idea, and maybe it's not worth doing if everyone things it's a waste. Let me know if any of my comments is confusing.

**Comment by hannahkane** [comment]
Good thoughts, @auremoser. I understand from @stephwright that your team will be discussing how you want the various kinds of Events to show up on the site as part of your strategy planning meeting on Oct 10-13. Maybe we could revisit this after that conversation and file new tickets for whatever comes out of that?

Closing this for now, with that expectation, but feel free to re-open if you need to / want to.
