### ISSUE TITLE
Login/Logout error

### ISSUE THREAD

**Issue by auremoser** [mozilla/science.mozilla.org#71]
### Context
Trying to use Abby's rad new event template, not sure the following problem is related but that was the impetus, issue #69. 

When I login on the home page and then navigate to "Community" it logs me out. 

### Procedure
* navigate to <http://mozillascience.org>
* select upper right `login`
* select "Community"
-> logout 
* select upper right `login` again
-> returns me to "home page"

### Caveats
This is how it works in Chrome, in incognito, it works fine! Not sure what it's storing that bugs up in Chrome default though :/ Feel free to close it, as it's kind of niche, but it's a weird issue.

### Gif

![login](https://cloud.githubusercontent.com/assets/1559703/12370560/4ce65370-bbe3-11e5-90a0-3011720ddf5e.gif)

**Comment by acabunoc** [comment]
Thanks!

Yeah, I've been noticing strange session issues. I thought they went away when we switched to redis but I guess not womp wormp :( As you've noticed, it should work if you don't visit `/community` before logging in.

I think since we precompile the html, our cdn caches the page. It should update when you're logged in, but something's up. Thanks for documenting this!!
