### ISSUE TITLE
Wireframes for Projects page

### ISSUE THREAD

**Issue by hannahkane** [mozilla/science.mozilla.org#97]
Goals/purpose + content to be discussed further.

@my-le - please drop the wireframes you've been working on here. Thank you!

@kaythaney @acabunoc @auremoser - please feel free to drop any notes or additional context for this page here, but let's also plan to discuss soon.

**Comment by my-le** [comment]
Inspired from Advocacy Fellows Page (https://advocacy.mozilla.org/open-web-fellows/): a secondary menu would allow to lighten and split content in different pages
For current Projects wireframes: Projects / About / FAQ.
Feel free to comment on Red Pen: https://redpen.io/p/kwe0b1b8415da9f6f4 
And below are the previews.

**Comment by acabunoc** [comment]
From the longer [design brief](https://docs.google.com/document/d/1Z2jNumwfLM0d4cgpeF5-N-mEwiGmcWYo4NXHIUIXr7w/edit#)

### Collaborate redesign - [mozillascience.org/collaborate](https://mozillascience.org/collaborate)
#### problem
Collaborate (mozillascience.org/collaborate) was launched as a collection of open source projects for science. We’ve found uptake in contributorship slow since most of our community is new to open source. 

#### main goals
fold in guides and learning resources to help:

1. potential contributors get involved and learn about open source
2. project leads make their projects more contributor friendly (README, CONTRIBUTING, etc)
spur contributorship - make it easier for those new to open source to get involved
  * related material: [Working Open Workshop resources](http://mozillascience.github.io/working-open-workshop/#handouts)

#### constraints
current architecture - if we move will have to port over existing projects / users
keep github integration around projects - it’s a nice onboarding step for new to open source contributors

**Comment by my-le** [comment]
Projects Page – Projects Part:

![01-msl-projects-wireframe-projects](https://cloud.githubusercontent.com/assets/10426601/13504330/479fe2c6-e174-11e5-8041-bf4e496bb50f.jpg)

**Comment by my-le** [comment]
Projects Page – About Part:

![02-msl-projects-wireframe-about](https://cloud.githubusercontent.com/assets/10426601/13504350/6835a8a4-e174-11e5-86ce-22a58b0804c5.jpg)

**Comment by my-le** [comment]
Projects Page – FAQ Part Option A:

![03-msl-projects-wireframe-faq-a](https://cloud.githubusercontent.com/assets/10426601/13504383/800432ac-e174-11e5-9291-486cb45cd8c7.jpg)

**Comment by my-le** [comment]
Projects Page – FAQ Part Option B

![03-msl-projects-wireframe-faq-b](https://cloud.githubusercontent.com/assets/10426601/13504394/97a279fa-e174-11e5-92cd-1377bf73d7e3.jpg)
:

**Comment by kristinashu** [comment]
I've added a little more detail to the project page wireframes and would love everyone's feedback: https://redpen.io/jc2e62ed8f6f3f6ef5

I've put in some rough copy sections but it would be helpful to get a better idea of how much copy you think we will have.

cc @hannahkane @xmatthewx @acabunoc @kaythaney @auremoser @zee-moz @stephwright

**Comment by kristinashu** [comment]
Please add any copy suggestions to the doc https://docs.google.com/a/mozilla.com/document/d/1k2Ds-iw4B_Sh5ae1areW1qfuLPtSqmgohtXYBkOi7r4/edit?usp=sharing
